### ISSUE TITLE
Seg fault in rkfs_ kills python kernel without error message or traceback

### ISSUE THREAD

**Issue by mountaindust** [hplgit/odespy#1]
Backtrace from gdb:

#0  0x69144891 in rkfs_ () from C:\Python27\lib\site-packages\odespy\_rkf45.pyd
#1  0x69146562 in rkf45_ () from C:\Python27\lib\site-packages\odespy\_rkf45.pyd
#2  0x691444d8 in advance_ () from C:\Python27\lib\site-packages\odespy\_rkf45.pyd
#3  0x69142291 in f2py_rout__rkf45_advance ()
   from C:\Python27\lib\site-packages\odespy\_rkf45.pyd
#4  0x69142c83 in fortran_call () from C:\Python27\lib\site-packages\odespy\_rkf45.pyd
#5  0x1e0650fe in python27!PyObject_Call () from C:\Windows\system32\python27.dll
#6  0x00000000 in ?? ()

I am working on making this reproducible, but so far, it only wants to occur in the middle of a ton of cython code after running for 2 hours.  I've had "unexpected kernel death" in a number of solvers, all of them adaptive methods (I haven't tried with non-adaptive methods).

Update: I've been able to reproduce the kernel crash on the first step when using Lsoda. As a result, I was able to step in with pdb while using some pure python code, and (accidentally, actually) get an error message: "Illegal input was detected, before taking any integration steps." This message repeats a couple of times with a suggested factor for scaling tolerance before you get "SystemExit: 1."  Maybe this is what then propagates up and crashes the kernel?  In normal running, you cannot catch whatever is crashing it, even with a bare "except:" clause.  The error message never appears either - probably because stdout doesn't get flushed - and all you see is the message "The kernel has died unexpectedly..." which prints to the screen over and over again every few seconds.

Something needs to be fixed here, so that such errors from the solver raise an exception with some information rather than a SystemExit.  At minimum, it would be nice if the kernel didn't crash and a readable error message was displayed.

Further examination of Lsoda with pdb always hangs the Spyder IDE on line 1086 in solvers.py.  value.dtype is determined to be dtype('float64') on line 1077, and requesting this information from the pdb prompt does not raise an error. My U0 array is rather long, (282568 in length), but I don't see how that would make a difference for this assignment. Windows can recover from the crash, and requesting information about self.dtype from pdb gives the following, somewhat cryptic error:

ipdb> self.dtype
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 569, in run
    self.update_remote_view()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 450, in update_remote_view
    remote_view = make_remote_view(ns, settings, more_excluded_names)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 70, in make_remote_view
    more_excluded_names=more_excluded_names)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 59, in get_remote_data
    excluded_names=excluded_names)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 237, in globalsfilter
    filters=filters))
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 202, in is_supported
    if not is_editable_type(value):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 115, in is_editable_type
    return get_color_name(value) not in (UNSUPPORTED_COLOR, CUSTOM_TYPE_COLOR)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 107, in get_color_name
    elif value.size == 1:
AttributeError: Lsoda instance has no attribute 'size'

dtype('float64')

Typing self.dtype again, or maybe anything else, hangs pdb indefinitely (thus the kernel death?).

**Comment by yoavram** [comment]
Great back and forth, thanks!
