### ISSUE TITLE
windows 7 installation

### ISSUE THREAD

**Issue by jmilhomens** [hplgit/odespy#3]
I could install odespy with the command: "python setup.py install build --compiler=ming32"

The command suggested  ("python setup.py install") gives the error "unable to find vcvarsall.bat". It happened already in two Windows 7 machines.

mingw32 needs to be installed of course.

I suggest adding this to the installation instructions. 

I don't know if this is the right way to give feed-back but I thought it was important to let you know. If compiling with mingw32 was suggested, it would have saved me a couple of hours of googling.

Thank you!

**Comment by rothnic** [comment]
Not sure if this came up for the person who submitted this issue, but I had to make [this modification](http://stackoverflow.com/a/25126133) to get ming32 to work.

**Comment by hplgit** [comment]
Thank you very much for pointing this out. I have updated the installation instructions accordingly.
